language: java
sudo: required
dist: trusty
jdk: oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
- ./gradlew assemble
- docker -v
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- set +e
- export REPO=aista/form-expert
- docker build -t $REPO:$TRAVIS_TAG -t $REPO:latest .
- docker push $REPO